### ISSUE TITLE
reference alignment is incorrect

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/qiime-default-reference#14]
A [QIIME Forum user](https://groups.google.com/d/msg/qiime-forum/UHtriq_l9OE/1H8E_OM3FqsJ) working with V2 sequences noticed that many more sequences were failing to be aligned with PyNAST in QIIME 1.9.0 than in QIIME 1.8.0. After some investigation, it turns out that the alignments packaged with Greengenes (and thus in the 0.1.0 and 0.1.1 releases of ``qiime-default-reference``) are not in fact the PyNAST aligned sequences, but rather are SSU aligned, and some positions are filtered. **We will be fixing this for ``qiime-default-reference 0.1.2``.**

This doesn't seem to be an issue when working with sequences generated from the 515F/806R primers (which is what I tested with when [I brought the question of switching](https://github.com/biocore/qiime/issues/1770) from the old core set to the 85% aligned OTUs), but it does appear to be a problem with V2 sequences (presumably from the 27F primer). 

For users working with non-515F/806R sequences, this means that PyNAST alignments will need to be regenerated. If you're using OTU tables that were generated with ``pick_open_reference_otus.py``, those should be regenerated, as the ``no_pynast_failures`` table will have many OTUs filtered from it. You'll need to first upgrade to ``qiime-default-reference 0.1.2``. Once that goes live, you can do that as follows:

```bash
pip install --upgrade qiime-default-reference
```

We'll follow up on this issue, the QIIME blog, and the QIIME Forum when this is ready.

**Comment by gregcaporaso** [comment]
I'm currently working on a fix for this. With [PyNAST-aligned versions of the 13_8 85% OTUs](https://github.com/biocore/qiime-default-reference/blob/issue-14/qiime_default_reference/gg_13_8_otus/rep_set_aligned/85_otus.pynast.fasta.gz), I'm still seeing slightly lower percent id matches for the V2 sequences ([data here](https://docs.google.com/spreadsheets/d/1g2oQfun6eKXHG3ZCj1cn42IROi96FLCdyUzyqroi20Q/pubhtml?gid=0&single=true), though the results are much better now than when comparing against ``qiime-default-reference 0.1.1``. However... not all of the 85% OTUs were align-able with PyNAST (I think) as I'm finding that filtering as follows results in fewer aligned than unaligned sequences:

```bash
filter_fasta.py -f $HOME/data/gg_13_8_otus/rep_set_aligned/gg_13_5_pynast.fasta -o $HOME/data/gg_13_8_otus/rep_set_aligned/85_otus.pynast.fasta -a $HOME/data/gg_13_8_otus/rep_set/85_otus.fasta
```

and that there are still sometimes very minor differences in the sequences if I unalign the aligned sequence and compare them against the corresponding sequences in ``gg_13_8/rep_set/85_otus.fasta``. 

I'm continuing to look into this, and am considering reverting to the core set for the time-being in ``qiime-default-reference 0.1.2`` (if the licensing allows that, which I'll be looking into). 

In the meantime, **the work-around for QIIME users working with non-515F/806R 16S primers** will be to align against the core set, which is available [here](http://greengenes.lbl.gov/Download/Sequence_Data/Fasta_data_files/core_set_aligned.fasta.imputed). This file path can be added as the value for ``pynast_template_alignment_fp`` in ``qiime_config``, as described [here](http://qiime.org/install/qiime_config.html).

**Comment by wasade** [comment]
@gregcaporaso, the following should do it (pynast aligned [here](ftp://ftp.microbio.me/greengenes_release/gg_13_5/gg_13_5_pynast.fasta.gz))

```bash
gunzip gg_13_5_pynast.fasta.gz
filter_fasta.py -f gg_13_5_pynast.fasta -o $HOME/data/gg_13_8_otus/rep_set_aligned/85_otus.pynast.fasta -a $HOME/data/gg_13_8_otus/rep_set/85_otus.fasta
```

**Comment by gregcaporaso** [comment]
Is that different than the command I posted above?

**Comment by wasade** [comment]
Not sure, is that input file the same as the file I linked? It isn't part
of the otus package hence the confusion

A length check may not be sufficient if pynast can trim 5' or 3'

**Comment by wasade** [comment]
Also, there were about 1500 seqs that didn't align with pynast as youve
noted

**Comment by gregcaporaso** [comment]
I think you forgot the link, but I pulled my file from secondgenome's [download page](http://greengenes.secondgenome.com/downloads/database/13_5), and the md5 is correct:

```
MD5 (gg_13_5_pynast.fasta.gz) = 24720085027c35132de0588fee518065
```

Ok, given that it's known that some of the sequences in 13_5 don't align with PyNAST (which would explain why I have fewer), and that the differences that I notice in the sequences are small and (based on spot-checks) in the ends of sequences, I think we're good with using this PyNAST 85% OTU alignment as the default template alignment. I'll work on building and testing this release, then testing with QIIME. 

Updated work-around: In the meantime, **the work-around for QIIME users working with non-515F/806R 16S primers** will be to align against the Greengenes 13_5 PyNAST 85% OTU alignment, which is available [here](https://github.com/biocore/qiime-default-reference/blob/issue-14/qiime_default_reference/gg_13_8_otus/rep_set_aligned/85_otus.pynast.fasta.gz). After downloading and unzipping that file, it's absolute file path can be added as the value for ``pynast_template_alignment_fp`` in ``qiime_config``, as described [here](http://qiime.org/install/qiime_config.html). This will achieve the same result as when we release ``qiime-default-reference 0.1.2``.

**Comment by gregcaporaso** [comment]
Blog post announcing this bug is [now live](https://qiime.wordpress.com/2015/04/15/qiime-1-9-0-bug-affecting-pynast-alignment-of-16s-amplicons-generated-with-non-515f806r-primers/).

**Comment by wasade** [comment]
Apparently github silently doesn't render FTP links, sorry about that. Thanks for getting this together, and yet more motivation for another GG release

**Comment by gregcaporaso** [comment]
In an additional test of PyNAST alignment of V2 sequences with the core set versus the PyNAST 85% OTU alignment added in #15, I find that only slightly more sequences fail to align with the PyNAST 85% OTU alignment than with the old core set. Details of my test follow. Since we don't have an inherent way to say which is better (i.e., it's possible that we want those additional sequences to fail), and we have complete understanding of how the PyNAST 85% OTU alignment was generated (which is not true for the core set), we'll move forward with the plan to use the PyNAST 85% OTU alignment as the default reference template alignment. 

My test was performed with the V2 sequences deposited under study id ``449`` in the QIIME database (the [Costello Whole Body](http://www.sciencemag.org/content/326/5960/1694.abstract)) dataset. I ran the following command to pick OTUs and perform PyNAST alignment against the PyNAST 85% OTU alignment:

```bash
$ pick_open_reference_otus.py -i /home/caporaso/analysis/whole-body/study_449_split_library_seqs.fna --suppress_taxonomy_assignment -aO 29 -o /home/caporaso/analysis/whole-body/or-otus
$ count_seqs.py -i "pynast_aligned_seqs/rep_set_*fasta"

204  : pynast_aligned_seqs/rep_set_failures.fasta (Sequence lengths (mean +/- std): 181.9706 +/- 56.2609)
10200  : pynast_aligned_seqs/rep_set_aligned.fasta (Sequence lengths (mean +/- std): 7682.0000 +/- 0.0000)
10404  : Total
```

This tells us that 204 sequences failed to align with PyNAST out of 10664 (there is one header line). 

Then, I re-aligned the representative sequences against the core set 

```bash
$ parallel_align_seqs_pynast.py -i /home/caporaso/analysis/whole-body/or-otus/rep_set.fna -o /home/caporaso/analysis/whole-body/or-otus/pynast_aligned_seqs_core_set --jobs_to_start 30 -t /data/qiime_software/core_set_aligned.fasta.imputed
$ count_seqs.py -i "pynast_aligned_seqs_core_set/rep_set_*fasta"

171  : pynast_aligned_seqs_core_set/rep_set_failures.fasta (Sequence lengths (mean +/- std): 166.0292 +/- 46.7550)
10233  : pynast_aligned_seqs_core_set/rep_set_aligned.fasta (Sequence lengths (mean +/- std): 7682.0000 +/- 0.0000)
10404  : Total
```

Also, it's important to note that different sequences failed to align with the two data sets (i.e., the sequences that fail to align against the core set are not a subset of the sequences that fail to align against the 85% PyNAST-aligned OTUs). 

```bash
# find the sequences that didn't align against the 85% PyNAST-aligned OTUs
# but did align against the core set
$ filter_fasta.py -f pynast_aligned_seqs/rep_set_failures.fasta -o pynast_aligned_seqs/failures-that-aligned-v-core-set.fasta -a pynast_aligned_seqs_core_set/rep_set_aligned.fasta
caporaso@bacon 08:07:58 or-otus$ count_seqs.py -i pynast_aligned_seqs/failures-that-aligned-v-core-set.fasta

47  : pynast_aligned_seqs/failures-that-aligned-v-core-set.fasta (Sequence lengths (mean +/- std): 256.3404 +/- 16.3086)
47  : Total

# find the sequences that didn't align against the core set
# but did align against the 85% PyNAST-aligned OTUs
$ filter_fasta.py -f pynast_aligned_seqs_core_set/rep_set_failures.fasta -o pynast_aligned_seqs_core_set/failures-that-aligned-v-pyn-85-otus.fasta -a pynast_aligned_seqs/rep_set_aligned.fasta
$ count_seqs.py -i pynast_aligned_seqs/failures-that-aligned-v-pyn-85-otus.fasta

14  : pynast_aligned_seqs/failures-that-aligned-v-pyn-85-otus.fasta (Sequence lengths (mean +/- std): 236.9286 +/- 11.0677)
14  : Total
```

I'm now investigating what those hit, and will follow up on this issue when I have time to analyze. 

```bash
$ parallel_blast.py -i /home/caporaso/analysis/whole-body/or-otus/pynast_aligned_seqs_core_set/failures-that-aligned-v-pyn-85-otus.fasta -o /home/caporaso/analysis/whole-body/or-otus/pynast_aligned_seqs_core_set/failures-that-aligned-v-pyn-85-otus-blast-results/ -b /data/blast/nt -O 10
$ parallel_blast.py -i /home/caporaso/analysis/whole-body/or-otus/pynast_aligned_seqs/failures-that-aligned-v-core-set.fasta -o /home/caporaso/analysis/whole-body/or-otus/pynast_aligned_seqs/failures-that-aligned-v-core-set-blast-results/ -b /data/blast/nt -O 10
```
